(() => {
const KEY='rootRpg_v06', LEGACY=['rootRpg_v04','rootRpg_v03','rootRpg_v02','rootSandboxCompanion_v02','rootSandbox_v01'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=()=>Math.random().toString(36).slice(2,9)+Date.now().toString(36).slice(-4);
const ico=(id,cls='')=>`<svg class="ico ${cls}"><use href="./icons.svg#${id}"></use></svg>`;
const ITEM_DEF={sword:{name:'Espada',icon:'sword'},boot:{name:'Bota',icon:'boot'},crossbow:{name:'Ballesta',icon:'crossbow'},torch:{name:'Antorcha',icon:'torch'},hammer:{name:'Martillo',icon:'hammer'},tea:{name:'Té',icon:'rest'},coin:{name:'Moneda',icon:'coin'},bag:{name:'Bolsa',icon:'bag'}};
const EMPTY_ITEMS=()=>({sword:0,boot:0,crossbow:0,torch:0,hammer:0,tea:0,coin:0,bag:0});
const VAGABONDS={
 thief:{name:'Thief',tagline:'Oportunismo, sigilo e información',species:'Mapache',portrait:'./art/thief.svg',ability:{name:'STEAL',text:'Interactúa con otro actor presente en tu claro para sustraer recursos, cartas, objetos o información cuando la situación lo permita.'},starting:{boot:1,torch:1,tea:1,sword:1},branches:[
  {id:'shadow',name:'Shadow',skills:[['thief_shadow_1','Sneak','Acceso a opciones de sigilo en eventos y misiones.'],['thief_shadow_2','Ghost','Reduce ciertas consecuencias negativas de infiltración.'],['thief_shadow_3','Master of Shadows','Abre soluciones especiales de infiltración avanzada.']]},
  {id:'opportunist',name:'Opportunist',skills:[['thief_opportunist_1','Scavenger','Mejores resultados en recompensas de saqueo.'],['thief_opportunist_2','Black Market','Desbloquea comerciantes, intercambios y recompensas especiales.'],['thief_opportunist_3','King of Thieves','Oportunidades únicas de contrabando, robo e información.']]},
  {id:'informant',name:'Informant',skills:[['thief_informant_1','Eavesdrop','Información adicional en ciertos encuentros.'],['thief_informant_2','Network','Mayor acceso a rumores de facciones conocidas.'],['thief_informant_3','Spymaster','Información oculta ocasional sobre amenazas y conflictos.']]}
 ]},
 ranger:{name:'Ranger',tagline:'Supervivencia, combate y exploración',species:'Zorro',portrait:'./art/ranger.svg',ability:{name:'HIDEOUT',text:'Puede retirarse, sobrevivir y recuperarse lejos de la civilización; conserva la identidad de reparación y recuperación del Ranger.'},starting:{boot:1,torch:1,sword:2,crossbow:1},branches:[
  {id:'pathfinder',name:'Pathfinder',skills:[['ranger_pathfinder_1','Tracker','Detecta rastros, amenazas e información adicional al explorar.'],['ranger_pathfinder_2','Pathfinder','Opciones especiales al viajar por zonas difíciles.'],['ranger_pathfinder_3','Master Explorer','Descubre rutas, encuentros o localizaciones excepcionales.']]},
  {id:'hunter',name:'Hunter',skills:[['ranger_hunter_1','Hunter','Mejora opciones de caza y persecución.'],['ranger_hunter_2','Ambusher','Desbloquea soluciones de emboscada.'],['ranger_hunter_3','Apex Hunter','Oportunidades especiales contra objetivos peligrosos.']]},
  {id:'survivor',name:'Survivor',skills:[['ranger_survivor_1','Field Repair','Mejora oportunidades de reparación y recuperación.'],['ranger_survivor_2','Endurance','Reduce penalizaciones de expediciones.'],['ranger_survivor_3','Unbreakable','Opciones exclusivas en supervivencia extrema.']]}
 ]},
 tinker:{name:'Tinker',tagline:'Creación, recuperación y recursos',species:'Ratón',portrait:'./art/tinker.svg',ability:{name:'DAY LABOR',text:'Recupera utilidad de recursos previamente usados o descartados; encuentra valor donde otros ven basura.'},starting:{boot:1,torch:1,hammer:1,bag:1},branches:[
  {id:'craftsman',name:'Craftsman',skills:[['tinker_craftsman_1','Repairman','Mejores opciones al reparar objetos.'],['tinker_craftsman_2','Craftsman','Desbloquea recetas y soluciones de fabricación.'],['tinker_craftsman_3','Master Artificer','Fabrica o restaura objetos excepcionales.']]},
  {id:'scavenger',name:'Scavenger',skills:[['tinker_scavenger_1','Salvage','Mejora recompensas de restos, ruinas o campos de batalla.'],['tinker_scavenger_2','Reclaim','Recupera determinados recursos especiales.'],['tinker_scavenger_3','Treasure from Trash','Descubre materiales excepcionales donde otros no podrían.']]},
  {id:'inventor',name:'Inventor',skills:[['tinker_inventor_1','Improvise','Soluciones alternativas en determinados eventos.'],['tinker_inventor_2','Contraption','Permite usar mecanismos especiales.'],['tinker_inventor_3','Inventor','Soluciones únicas de ingeniería y artefactos.']]}
 ]}
};
const SKILLS=Object.fromEntries(Object.entries(VAGABONDS).flatMap(([type,v])=>v.branches.flatMap(branch=>branch.skills.map((x,i)=>[x[0],{id:x[0],name:x[1],characterType:type,branch:branch.id,branchName:branch.name,tier:i+1,description:x[2],effect:x[2],unlockRequirements:i?[`${type}_${branch.id}_${i}`]:[]}]))));
const FACTIONS={Marquesado:{icon:'faction-cat',className:'cat',color:'var(--cat)',outcomes:['Batalló','Reclutó','Construyó','Movió','Ganó territorio','Perdió territorio']},Eyrie:{icon:'faction-bird',className:'bird',color:'var(--bird)',outcomes:['Batalló','Reclutó','Construyó','Movió','Ganó territorio','Perdió territorio']},Alianza:{icon:'faction-alliance',className:'alliance',color:'var(--alliance)',outcomes:['Extendió simpatía','Revuelta','Reclutó','Movilizó','Ganó territorio','Perdió territorio']}};
const SUITS={mouse:{name:'Ratón',icon:'suit-mouse'},rabbit:{name:'Conejo',icon:'suit-rabbit'},fox:{name:'Zorro',icon:'suit-fox'},bird:{name:'Ave',icon:'suit-bird'}};
const STATES=[['Alerta','alert'],['Bloqueo','lock'],['Tensión','sword'],['Escasez','bread'],['Fortificado','shield'],['Revuelta','leaf'],['Caos','flame']];
const LANDMARKS=[['forge','Forja Legendaria','forge','Artesanía, reparación y mejoras.'],['market','Mercado Negro','market','Información, objetos y contactos.'],['ruins','Ciudad Perdida','ruins','Reliquias, rutas y secretos.'],['tree','Árbol Ancestral','tree','Refugio neutral y mediación.']];
const ACTIONS=[['move','Mover','move',1],['observe','Observar','eye',1],['talk','Hablar','chat',1],['investigate','Investigar','search',1],['trade','Comerciar','coin',1],['infiltrate','Infiltrar','key',1],['combat','Combatir','sword',1],['explore','Explorar','torch',1],['help','Apoyar facción','handshake',1],['craft','Fabricar / reparar','hammer',1],['rest','Descansar','rest',2],['free','Acción libre','spark',1]];

function fresh(){return{version:'0.6',onboarded:false,playerName:'',campaign:'Crónicas del Bosque',day:1,time:0,phase:'player',actions:[],character:{id:uid(),name:'',vagabondType:null,startingItems:{},currentItems:EMPTY_ITEMS(),specialAbility:null,skills:[],milestones:[],reputation:{Marquesado:0,Eyrie:0,Alianza:0},discoveries:[],importantEvents:[],clear:''},bots:{Marquesado:true,Eyrie:true,Alianza:false},world:{day:1,resolved:{},records:{}},orderHistory:[],states:[],rumors:[],missions:[],landmarks:LANDMARKS.map(x=>({id:x[0],name:x[1],icon:x[2],description:x[3],level:0,clear:''})),log:[]}}
function setupCharacter(type){const v=VAGABONDS[type];S.character.vagabondType=type;S.character.specialAbility={...v.ability};S.character.startingItems={...v.starting};S.character.currentItems={...EMPTY_ITEMS(),...v.starting};S.character.skills=[];S.character.milestones=[]}
function migrate(o){const n=fresh();if(!o)return n;n.onboarded=!!o.onboarded;n.playerName=o.playerName||o.character?.name||'';n.campaign=o.campaign||n.campaign;n.day=o.day||1;n.time=o.time||0;n.phase=o.phase||'player';n.actions=o.actions||[];n.bots=o.bots||n.bots;n.world=o.world||n.world;n.orderHistory=o.orderHistory||[];n.states=o.states||[];n.rumors=o.rumors||[];n.missions=(o.missions||[]).map(m=>({...m,stage:m.stage||0,steps:m.steps||null}));n.landmarks=o.landmarks||n.landmarks;n.log=o.log||[];const old=o.character||{};const type=old.vagabondType||'thief';setupInto(n,type);n.character.id=old.id||uid();n.character.name=n.playerName;n.character.clear=old.clear||'';n.character.skills=Array.isArray(old.skills)?old.skills.filter(x=>typeof x==='string'&&SKILLS[x]):[];n.character.milestones=old.milestones||[];n.character.reputation=old.reputation||o.reputations||o.rep||n.character.reputation;n.character.discoveries=old.discoveries||[];n.character.importantEvents=old.importantEvents||[];const inv=old.currentItems||o.inventory||o.inv;if(inv)n.character.currentItems={...n.character.currentItems,...inv};return n}
function setupInto(n,type){const v=VAGABONDS[type];n.character.vagabondType=type;n.character.specialAbility={...v.ability};n.character.startingItems={...v.starting};n.character.currentItems={...EMPTY_ITEMS(),...v.starting}}
let S;try{S=JSON.parse(localStorage.getItem(KEY));if(!S){for(const k of LEGACY){const o=JSON.parse(localStorage.getItem(k));if(o){S=migrate(o);break}}}if(!S)S=fresh()}catch(e){S=fresh()}
const sheet={bg:$('#sheetBackdrop'),title:$('#sheetTitle'),sub:$('#sheetSub'),content:$('#sheetContent')};
function save(){localStorage.setItem(KEY,JSON.stringify(S));const c=$('#saveChip');if(c){c.textContent='Guardado';clearTimeout(save.t);save.t=setTimeout(()=>c.textContent='Autoguardado',700)}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1400)}
function log(t,i='scroll'){S.log.unshift({day:S.day,text:t,icon:i});save()}
function openSheet(t,s,h,bind){sheet.title.textContent=t;sheet.sub.textContent=s||'';sheet.content.innerHTML=h+`<button class="btn secondary" data-close style="width:100%;margin-top:14px">Cerrar</button>`;sheet.bg.classList.add('open');if(bind)bind(sheet.content);sheet.content.querySelector('[data-close]').onclick=()=>sheet.bg.classList.remove('open')}
sheet.bg.onclick=e=>{if(e.target===sheet.bg)sheet.bg.classList.remove('open')};
function choice(t,s,arr,cb){openSheet(t,s,`<div class="choice-grid">${arr.map((x,i)=>`<button class="choice-btn" data-c="${i}">${x.icon?ico(x.icon):''}<span>${esc(x.label)}</span></button>`).join('')}</div>`,r=>r.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>cb(arr[+b.dataset.c])))}
function chooseClear(t,cb){choice(t,'Toca el claro físico del tablero.',Array.from({length:12},(_,i)=>({label:String(i+1)})),x=>cb(x.label))}
function hasSkill(id){return S.character.skills.includes(id)}
function addMilestone(type,label,source='world'){if(S.character.milestones.some(m=>m.type===type&&m.label===label))return;S.character.milestones.push({id:uid(),type,label,source,day:S.day,dateUnlocked:new Date().toISOString()});log('Hito: '+label,'medal');toast('Nueva habilidad disponible')}
function availableSkills(){const type=S.character.vagabondType;if(!type)return[];return Object.values(SKILLS).filter(x=>x.characterType===type&&!hasSkill(x.id)&&x.unlockRequirements.every(hasSkill))}
function canUnlock(){return S.character.milestones.length>S.character.skills.length&&availableSkills().length}
function unlockSkill(id){if(!SKILLS[id]||hasSkill(id)||!canUnlock())return;S.character.skills.push(id);log('Habilidad adquirida: '+SKILLS[id].name,'star');save();renderAll();toast('Nueva habilidad adquirida')}
function repLabel(v){return v<=-3?'Enemigo':v===-2?'Hostil':v===-1?'Sospechoso':v===0?'Neutral':v===1?'Conocido':v===2?'Confiable':'Aliado'}
function activeBots(){return Object.keys(S.bots).filter(k=>S.bots[k])}
function ensureWorld(){if(!S.world||S.world.day!==S.day)S.world={day:S.day,resolved:{},records:{}}}
function recordAction(label,icon,cost=1,meta='',effect){if(S.phase==='world')return toast('Primero resuelve la Fase del Mundo');if(S.time+cost>4)return toast('No queda suficiente tiempo');S.time+=cost;if(effect)effect();S.actions.push({day:S.day,label,icon,cost,meta,clear:S.character.clear});log(label+(meta?' · '+meta:''),icon);if(S.time>=4){S.phase='world';ensureWorld()}save();renderAll();return true}
function resolveAction(id){
 if(id==='move')return chooseClear('Mover',c=>{S.character.clear=c;recordAction('Mover al claro '+c,'move',1);sheet.bg.classList.remove('open')});
 const map={observe:['Observar','eye',['Entorno','Facción','Ruta','Rumor','Lugar']],talk:['Hablar','chat',['Habitante','Comerciante','Patrulla','Contacto','Desconocido']],investigate:['Investigar','search',['Rumor','Facción','Estado','Ruina','Rastro']],trade:['Comerciar','coin',['Comprar','Vender','Sobornar','Contratar ayuda']],infiltrate:['Infiltrar','key',['Escabullirse','Robar','Sabotear','Plantar evidencia']],combat:['Combatir','sword',['Marquesado','Eyrie','Alianza','Otro enemigo']],explore:['Explorar','torch',['Ruina','Lugar mítico','Ruta']],help:['Apoyar facción','handshake',['Marquesado','Eyrie','Alianza']],craft:['Fabricar / reparar','hammer',['Reparar','Fabricar','Mejorar']],rest:['Descansar','rest',['Refugio','Campamento']],free:['Acción libre','spark',['Sigilo','Preparación','Entorno','Objeto','Otra']]};
 const x=map[id];choice(x[0],'Elige sin escribir.',x[2].map(label=>({label})),v=>{let cost=id==='rest'?2:1;if(id==='craft'&&!S.character.currentItems.hammer&&!hasSkill('tinker_craftsman_1'))return toast('Necesitas Martillo o Repairman');recordAction(x[0],x[1],cost,v.label);sheet.bg.classList.remove('open')});
}
function renderActions(){const b=$('#actionGrid');b.innerHTML=ACTIONS.map(a=>`<button class="action-btn" data-a="${a[0]}"><div class="action-icon">${ico(a[2])}</div><div><div class="action-label">${a[1]}</div><div class="action-cost">${a[3]} tiempo</div></div></button>`).join('');b.querySelectorAll('[data-a]').forEach(x=>x.onclick=()=>resolveAction(x.dataset.a))}
function renderHeader(){const v=VAGABONDS[S.character.vagabondType];$('#heroName').textContent=S.campaign;$('#heroSubtitle').textContent=`Día ${S.day} · ${S.character.name||'Sin Vagabundo'}${v?' · '+v.name:''}`;$('#heroHp').parentElement.style.display='none';$('#heroXp').parentElement.style.display='none';$('#heroLevel').parentElement.style.display='none';$('#heroClear').textContent=S.character.clear||'—';$('#timeText').textContent=S.time+' / 4';$$('#timePips .time-pip').forEach((p,i)=>p.classList.toggle('on',i<S.time))}
function renderToday(){const a=S.actions.filter(x=>x.day===S.day),b=$('#todayTimeline');$('#todayCount').textContent=a.length+' acciones';b.innerHTML=a.length?a.map(x=>`<div class="timeline-item"><div class="timeline-icon">${ico(x.icon||'spark')}</div><div><div class="timeline-title">${esc(x.label)}</div><div class="timeline-meta">${esc(x.meta||'')}${x.clear?' · Claro '+x.clear:''}</div></div><span class="tag">${x.cost}t</span></div>`).join(''):'<div class="empty">El día está abierto. Elige cualquier acción.</div>';$('#endDayBtn').style.display=S.phase==='world'?'none':'block'}
function renderSheet(){const b=$('#vagabondSheet'),v=VAGABONDS[S.character.vagabondType];if(!v){b.innerHTML='<div class="empty">Crea tu Vagabundo para comenzar.</div>';return}$('#vagabondTypeLabel').textContent=v.name+' · '+v.tagline;b.innerHTML=`<div class="vagabond-sheet"><div class="vagabond-portrait"><img src="${v.portrait}" alt="${v.name}"></div><div class="vagabond-sheet-copy"><div class="eyebrow dark-eyebrow">${v.species} · ${v.name}</div><h2>${esc(S.character.name)}</h2><p>${v.tagline}</p><div class="ability-card"><span>Habilidad única</span><strong>${v.ability.name}</strong><p>${v.ability.text}</p></div></div></div>`}
function renderInventory(){const b=$('#inventoryGrid');b.innerHTML=Object.entries(ITEM_DEF).map(([id,d])=>`<div class="inv"><div class="inv-icon">${ico(d.icon)}</div><div class="inv-name">${d.name}</div><div class="inv-count">×${S.character.currentItems[id]||0}</div></div>`).join('')}
function renderSkills(){const b=$('#skillTree'),v=VAGABONDS[S.character.vagabondType];if(!v){b.innerHTML='';return}const avail=availableSkills();$('#skillStatus').textContent=canUnlock()?'nueva habilidad disponible':S.character.skills.length+' adquiridas';b.innerHTML=`<div class="skill-map"><div class="skill-map-root"><span>${v.name}</span><strong>${v.ability.name}</strong></div><div class="skill-branches">${v.branches.map(br=>`<div class="skill-branch"><h4>${br.name}</h4>${br.skills.map(x=>{const sk=SKILLS[x[0]],on=hasSkill(sk.id),ok=avail.some(a=>a.id===sk.id)&&canUnlock();return`<button class="skill-node ${on?'unlocked':ok?'available':'locked'}" data-skill="${sk.id}" ${ok?'':'disabled'}><span>${on?'✓':ok?'○':'×'}</span><div><strong>${sk.name}</strong><small>${sk.description}</small></div></button>`}).join('')}</div>`).join('')}</div></div>`;b.querySelectorAll('[data-skill]').forEach(x=>x.onclick=()=>unlockSkill(x.dataset.skill))}
function renderMilestones(){const b=$('#milestoneList');const m=S.character.milestones;b.innerHTML=m.length?m.slice().reverse().map(x=>`<div class="timeline-item"><div class="timeline-icon">${ico('medal')}</div><div><div class="timeline-title">${esc(x.label)}</div><div class="timeline-meta">Día ${x.day} · ${esc(x.source)}</div></div></div>`).join(''):'<div class="empty">Los hitos aparecen al completar misiones, descubrir lugares, mejorar relaciones y vivir eventos importantes.</div>'}
function renderRep(){const b=$('#reputationList');b.innerHTML=Object.entries(S.character.reputation).map(([n,v])=>`<div class="rep-card"><div class="rep-top"><div class="rep-title"><div class="faction-seal ${FACTIONS[n].className}">${ico(FACTIONS[n].icon)}</div><div><div class="rep-name">${n}</div><div class="rep-state">${repLabel(v)}</div></div></div><strong>${v>0?'+':''}${v}</strong></div><div class="rep-actions"><button class="chip" data-rep="${n}" data-d="-1">−1</button><button class="chip" data-rep="${n}" data-d="1">+1</button></div></div>`).join('');b.querySelectorAll('[data-rep]').forEach(x=>x.onclick=()=>{const n=x.dataset.rep,d=+x.dataset.d,old=S.character.reputation[n];S.character.reputation[n]=clamp(old+d,-3,3);if(Math.abs(S.character.reputation[n])>=2)addMilestone('reputation',`${n}: ${repLabel(S.character.reputation[n])}`,'reputación');save();renderAll()})}
function skillOptionsForMission(m){const type=S.character.vagabondType,out=[];if(type==='thief'){if(hasSkill('thief_shadow_1'))out.push(['INFILTRARSE','thief_shadow_1']);if(hasSkill('thief_informant_1'))out.push(['ESCUCHAR','thief_informant_1']);if(hasSkill('thief_opportunist_1'))out.push(['SAQUEAR','thief_opportunist_1'])}if(type==='ranger'){if(hasSkill('ranger_pathfinder_1'))out.push(['RASTREAR','ranger_pathfinder_1']);if(hasSkill('ranger_hunter_1'))out.push(['PERSEGUIR','ranger_hunter_1']);if(hasSkill('ranger_survivor_1'))out.push(['RESISTIR','ranger_survivor_1'])}if(type==='tinker'){if(hasSkill('tinker_inventor_1'))out.push(['IMPROVISAR','tinker_inventor_1']);if(hasSkill('tinker_scavenger_1'))out.push(['RECUPERAR','tinker_scavenger_1']);if(hasSkill('tinker_craftsman_1'))out.push(['REPARAR','tinker_craftsman_1'])}return out}
function missionSteps(m){if(m.steps)return m.steps;const target=m.suit==='fox'?'un claro zorro':m.suit==='rabbit'?'un claro conejo':m.suit==='mouse'?'un claro ratón':'el territorio afectado';return[{title:'Seguir la pista',text:'Investiga el rumor y confirma qué está ocurriendo.'},{title:'Llegar al objetivo',text:'Localiza '+target+' en el tablero físico.'},{title:'Resolver la escena',text:'Elige cómo intervenir y aplica el resultado a la mesa.'}]}
function renderMissions(){const b=$('#missionsList'),a=S.missions.filter(m=>m.status==='active');$('#missionCounter').textContent=a.length+' activas';if(!a.length){b.innerHTML='<div class="empty">Las Cartas de Orden pueden abrir historias jugables.</div>';return}b.innerHTML='';a.forEach(m=>{m.steps=missionSteps(m);m.stage=m.stage||0;const f=FACTIONS[m.origin]||FACTIONS.Marquesado,d=document.createElement('div');d.className='mission';const done=m.stage>=m.steps.length,opts=skillOptionsForMission(m);d.innerHTML=`<div class="mission-ribbon" style="background:${f.color}"></div><div class="mission-inner"><div class="mission-kicker">${esc(m.origin)} · ${SUITS[m.suit]?.name||''}</div><div class="mission-title">${esc(m.title)}</div><div class="mission-objective">${esc(m.objective)}</div><div class="quest-steps">${m.steps.map((s,i)=>`<div class="quest-step ${i<m.stage?'done':i===m.stage?'current':''}"><span>${i<m.stage?'✓':i+1}</span><div><strong>${s.title}</strong><small>${s.text}</small></div></div>`).join('')}</div>${!done?`<div class="mission-actions"><button class="btn" data-advance>Completar etapa</button></div>`:`<div class="mission-actions"><button class="btn gold" data-finish>Cobrar recompensa</button></div>`}${opts.length&&m.stage===m.steps.length-1?`<div class="skill-solutions"><small>Opciones de tu Vagabundo</small>${opts.map(o=>`<button class="chip active" data-option="${o[0]}">${o[0]}</button>`).join('')}</div>`:''}</div>`;d.querySelector('[data-advance]')?.addEventListener('click',()=>{m.stage++;log(`Misión: ${m.title} · etapa ${m.stage}/${m.steps.length}`,'search');save();renderAll()});d.querySelectorAll('[data-option]').forEach(x=>x.onclick=()=>{m.usedSkill=x.dataset.option;toast(x.dataset.option+' habilitado por tu Vagabundo')});d.querySelector('[data-finish]')?.addEventListener('click',()=>{m.status='completed';if(m.reward&&ITEM_DEF[m.reward])S.character.currentItems[m.reward]=(S.character.currentItems[m.reward]||0)+1;addMilestone('mission','Misión completada: '+m.title,'misión');log('Misión cumplida: '+m.title,'star');save();renderAll()});b.appendChild(d)})}
function renderRumors(){const b=$('#rumorsList');$('#rumorCounter').textContent=S.rumors.length+' / 3';b.innerHTML=S.rumors.length?'':'<div class="empty">Las órdenes todavía no han dejado rumores activos.</div>';S.rumors.forEach((r,i)=>{const d=document.createElement('div');d.className='rumor-card';d.innerHTML=`<div class="rumor-copy">“${esc(r.text)}”</div><div class="btn-row"><button class="btn" data-follow>Seguir pista</button><button class="btn secondary" data-drop>Dejar morir</button></div>`;d.querySelector('[data-follow]').onclick=()=>{const m=r.seed||missionDraft(r.origin,r.suit,['Movió']);m.stage=0;m.steps=null;S.missions.push(m);S.rumors.splice(i,1);recordAction('Seguir rumor','search',1,r.text);renderAll()};d.querySelector('[data-drop]').onclick=()=>{S.rumors.splice(i,1);save();renderAll()};b.appendChild(d)})}
function rewardFor(o){return({'Batalló':'sword','Reclutó':'bag','Construyó':'hammer','Movió':'boot','Movilizó':'boot','Ganó territorio':'crossbow','Perdió territorio':'tea','Extendió simpatía':'coin','Revuelta':'torch'})[o]||'coin'}
function missionDraft(origin,suit,outcomes){const p=outcomes[0]||'Movió',name={'Batalló':'Tras las líneas','Reclutó':'Nombres en la lista','Construyó':'Suministros desviados','Movió':'Rastro en los caminos','Movilizó':'Mensajeros en tránsito','Ganó territorio':'Nueva frontera','Perdió territorio':'Vacío de poder','Extendió simpatía':'Mensajes bajo la corteza','Revuelta':'Después de las llamas'}[p]||'Oportunidad del bosque';return{id:uid(),day:S.day,origin,suit,title:name,objective:`Investiga las consecuencias de ${origin} tras: ${outcomes.join(', ')||'movimientos recientes'}.`,reward:rewardFor(p),status:'active',stage:0,steps:null}}
function rumorDraft(origin,suit,outcomes,m){return{id:uid(),day:S.day,origin,suit,text:`${origin} está alterando el equilibrio en territorio ${SUITS[suit]?.name||'del bosque'}: ${outcomes.join(', ')||'hay movimientos extraños'}.`,seed:m}}
function renderBots(){ensureWorld();const b=$('#botList');b.innerHTML='';activeBots().forEach(n=>{const f=FACTIONS[n],r=S.world.records[n],d=document.createElement('div');d.className='order-card '+f.className;d.innerHTML=`<div class="order-ribbon"></div><div class="order-card-body"><div class="order-card-head"><div class="order-faction"><div class="faction-seal ${f.className}">${ico(f.icon)}</div><strong>${n}</strong></div><span class="tag">${r?SUITS[r.suit].name:'Pendiente'}</span></div><div class="order-card-actions"><button class="btn" data-bot ${S.phase!=='world'?'disabled':''}>${r?'Editar':'Registrar orden'}</button></div></div>`;d.querySelector('[data-bot]').onclick=()=>openBot(n);b.appendChild(d)});if(S.phase==='world'&&activeBots().every(n=>S.world.resolved[n])){const x=document.createElement('button');x.className='btn gold';x.textContent='Procesar consecuencias';x.onclick=harvest;b.appendChild(x)}}
function openBot(n){const f=FACTIONS[n],d={suit:S.world.records[n]?.suit||null,outcomes:S.world.records[n]?.outcomes||[]};openSheet(n,'Carta de Orden + cambios reales.',`<div class="suit-row">${Object.entries(SUITS).map(([id,s])=>`<button class="suit-btn" data-s="${id}">${ico(s.icon)}</button>`).join('')}</div><div class="choice-grid" style="margin-top:12px">${f.outcomes.map((o,i)=>`<button class="choice-btn" data-o="${i}">${o}</button>`).join('')}</div><button class="btn" id="sealOrder" style="width:100%;margin-top:12px">Sellar orden</button>`,r=>{r.querySelectorAll('[data-s]').forEach(x=>x.onclick=()=>{d.suit=x.dataset.s;r.querySelectorAll('[data-s]').forEach(y=>y.classList.toggle('selected',y===x))});r.querySelectorAll('[data-o]').forEach(x=>x.onclick=()=>{const o=f.outcomes[+x.dataset.o];d.outcomes=d.outcomes.includes(o)?d.outcomes.filter(z=>z!==o):[...d.outcomes,o];x.classList.toggle('selected')});$('#sealOrder').onclick=()=>{if(!d.suit)return toast('Elige el palo');S.world.records[n]=d;S.world.resolved[n]=true;sheet.bg.classList.remove('open');save();renderAll()}})}
function harvest(){const seeds=activeBots().map(n=>({origin:n,...S.world.records[n]}));seeds.forEach(s=>{S.orderHistory.unshift({id:uid(),day:S.day,...s});const m=missionDraft(s.origin,s.suit,s.outcomes),r=rumorDraft(s.origin,s.suit,s.outcomes,m);if(S.rumors.length<3)S.rumors.push(r)});S.day++;S.time=0;S.phase='player';S.world={day:S.day,resolved:{},records:{}};log('El bosque avanza. Nuevos rumores han surgido.','world');save();renderAll();switchView('descubrir')}
function renderOrders(){renderBots();const b=$('#orderHistoryList');b.innerHTML=S.orderHistory.slice(0,8).map(o=>`<div class="timeline-item"><div class="timeline-icon">${ico(SUITS[o.suit]?.icon||'card')}</div><div><div class="timeline-title">${o.origin} · ${SUITS[o.suit]?.name||''}</div><div class="timeline-meta">${(o.outcomes||[]).join(' · ')} · Día ${o.day}</div></div></div>`).join('')||'<div class="empty">Sin órdenes archivadas.</div>'}
function renderStates(){const b=$('#statesList');b.innerHTML=S.states.map((s,i)=>`<div class="item"><div class="item-head"><strong>Claro ${s.clear} · ${s.name}</strong><button class="chip" data-r="${i}">Resolver</button></div></div>`).join('')||'<div class="empty">Sin estados especiales.</div>';b.querySelectorAll('[data-r]').forEach(x=>x.onclick=()=>{S.states.splice(+x.dataset.r,1);save();renderStates()})}
function renderLandmarks(){const b=$('#landmarksList');b.innerHTML='';S.landmarks.forEach(l=>{const d=document.createElement('div');d.className='landmark';d.innerHTML=`<div class="landmark-top"><div class="landmark-icon">${ico(l.icon)}</div><div><div class="landmark-name">${l.name}</div><div class="landmark-desc">${l.description}</div></div><span class="tag">${l.clear?'Claro '+l.clear:'Oculto'}</span></div><div class="landmark-actions"><button class="chip" data-land>${l.clear?'Explorar':'Revelar'}</button></div>`;d.querySelector('[data-land]').onclick=()=>{if(!l.clear)return chooseClear('Ubicar '+l.name,c=>{l.clear=c;addMilestone('discovery','Descubrió '+l.name,'descubrimiento');sheet.bg.classList.remove('open');save();renderAll()});l.level=clamp((l.level||0)+1,0,3);if(l.level===1)addMilestone('discovery','Visitó '+l.name,'descubrimiento');recordAction('Explorar '+l.name,l.icon,1);renderAll()};b.appendChild(d)})}
function renderHistory(){const b=$('#historyList');b.innerHTML=S.log.slice(0,80).map(x=>`<div class="timeline-item"><div class="timeline-icon">${ico(x.icon||'scroll')}</div><div><div class="timeline-title">${esc(x.text)}</div><div class="timeline-meta">Día ${x.day}</div></div></div>`).join('')||'<div class="empty">El bosque todavía no tiene historia.</div>'}
function renderWorldBanner(){const b=$('#worldBanner');b.innerHTML=S.phase==='world'?'<div class="world-banner"><div><h3>Fase del Mundo</h3><p>Resuelve las Cartas de Orden.</p></div><button class="btn secondary" id="goOrders">Ir a Órdenes</button></div>':'';$('#goOrders')?.addEventListener('click',()=>switchView('mundo'))}
function renderAll(){renderHeader();renderActions();renderToday();renderWorldBanner();renderSheet();renderInventory();renderSkills();renderRep();renderMilestones();renderOrders();renderStates();renderRumors();renderMissions();renderLandmarks();renderHistory()}
function switchView(v){$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));scrollTo({top:0,behavior:'smooth'})}
$$('.nav-btn').forEach(x=>x.onclick=()=>switchView(x.dataset.view));
$('#endDayBtn').onclick=()=>{S.phase='world';ensureWorld();save();renderAll()};
$('#addStateBtn').onclick=()=>chooseClear('Estado del claro',c=>choice('Estado','Elige uno.',STATES.map(x=>({label:x[0],icon:x[1]})),x=>{S.states=S.states.filter(s=>s.clear!==c);S.states.push({clear:c,name:x.label});sheet.bg.classList.remove('open');save();renderAll()}));
$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='root-rpg-'+(S.character.name||'campana')+'.json';a.click()};
$('#importInput').onchange=async e=>{try{S=migrate(JSON.parse(await e.target.files[0].text()));S.onboarded=true;save();renderAll();toast('Campaña importada')}catch(_){toast('Archivo no válido')}};
$('#resetBtn').onclick=()=>{if(confirm('¿Crear una nueva campaña?')){S=fresh();save();renderAll();showCreator()}};
$('#settingsBtn').onclick=()=>openSheet('Ajustes','Campaña persistente.',`<div class="setting-row"><div><strong>Vagabundo</strong><div class="meta">${VAGABONDS[S.character.vagabondType]?.name||'Sin elegir'}</div></div><span class="tag">v0.6</span></div><div class="setting-row"><div><strong>Alianza Automatizada</strong></div><button class="chip" id="allianceToggle">${S.bots.Alianza?'Activa':'Inactiva'}</button></div>`,()=>$('#allianceToggle').onclick=()=>{S.bots.Alianza=!S.bots.Alianza;save();sheet.bg.classList.remove('open');renderAll()});

let draft={name:'',type:null};
function showCreator(step=1){$('#onboarding').classList.add('open');$('#creatorStepName').hidden=step!==1;$('#creatorStepType').hidden=step!==2;$('#creatorStepConfirm').hidden=step!==3;if(step===1){$('#playerName').value=draft.name||S.character.name||'';setTimeout(()=>$('#playerName').focus(),50)}if(step===2)renderPicker();if(step===3)renderConfirm()}
function renderPicker(){const b=$('#vagabondPicker');b.innerHTML=Object.entries(VAGABONDS).map(([id,v])=>`<button class="vagabond-choice ${draft.type===id?'selected':''}" data-v="${id}"><div class="vagabond-choice-art"><img src="${v.portrait}" alt="${v.name}"></div><div class="vagabond-choice-copy"><span>${v.name}</span><strong>${v.tagline}</strong><small>${v.ability.name} · ${Object.entries(v.starting).map(([k,n])=>ITEM_DEF[k].name+' ×'+n).join(' · ')}</small></div></button>`).join('');b.querySelectorAll('[data-v]').forEach(x=>x.onclick=()=>{draft.type=x.dataset.v;showCreator(3)})}
function renderConfirm(){const v=VAGABONDS[draft.type];$('#creatorSummary').innerHTML=`<div class="creator-confirm"><img src="${v.portrait}" alt=""><div><div class="eyebrow dark-eyebrow">${v.name}</div><h3>${esc(draft.name)}</h3><p>${v.tagline}</p><div class="ability-card"><span>${v.ability.name}</span><p>${v.ability.text}</p></div></div></div>`}
$('#creatorNextBtn').onclick=()=>{draft.name=$('#playerName').value.trim();if(!draft.name)return toast('Escribe el nombre del personaje');showCreator(2)};
$('#creatorBackBtn').onclick=()=>showCreator(1);$('#creatorEditBtn').onclick=()=>showCreator(2);
$('#startCampaignBtn').onclick=()=>{if(!draft.name||!draft.type)return;S=fresh();S.playerName=draft.name;S.character.name=draft.name;setupCharacter(draft.type);S.campaign='Crónicas de '+draft.name;S.onboarded=true;log(draft.name+' entra al bosque como '+VAGABONDS[draft.type].name+'.','paw');save();$('#onboarding').classList.remove('open');renderAll();chooseClear('¿Dónde comienzas?',c=>{S.character.clear=c;sheet.bg.classList.remove('open');save();renderAll()})};

ensureWorld();renderAll();if(!S.onboarded||!S.character.vagabondType)showCreator();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
})();